const facet = {
  "0": {
    Kerala: 0,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "1": {
    Kerala: 1,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "2": {
    Kerala: 1,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "3": {
    Kerala: 1,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "4": {
    Kerala: 2,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "5": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "6": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "7": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "8": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "9": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "10": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "11": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "12": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "13": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "14": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "15": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "16": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "17": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "18": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "19": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "20": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "21": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "22": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "23": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "24": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "25": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "26": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "27": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "28": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "29": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "30": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "31": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "32": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 0,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "33": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 1,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "34": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 0,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 0,
    Delhi: 2,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "35": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 6,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 0,
    Rajasthan: 0,
    Haryana: 14,
    Delhi: 2,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "36": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 7,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 1,
    Rajasthan: 0,
    Haryana: 14,
    Delhi: 2,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "37": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 7,
    Ladakh: 0,
    "Tamil Nadu": 0,
    Telangana: 1,
    Rajasthan: 0,
    Haryana: 14,
    Delhi: 3,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "38": {
    Kerala: 3,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 7,
    Ladakh: 2,
    "Tamil Nadu": 1,
    Telangana: 1,
    Rajasthan: 0,
    Haryana: 14,
    Delhi: 3,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "39": {
    Kerala: 8,
    Maharashtra: 0,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 0,
    Karnataka: 0,
    "Uttar Pradesh": 8,
    Ladakh: 2,
    "Tamil Nadu": 1,
    Telangana: 1,
    Rajasthan: 0,
    Haryana: 14,
    Delhi: 3,
    Punjab: 0,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "40": {
    Kerala: 9,
    Maharashtra: 2,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 1,
    Karnataka: 1,
    "Uttar Pradesh": 9,
    Ladakh: 3,
    "Tamil Nadu": 1,
    Telangana: 1,
    Rajasthan: 0,
    Haryana: 14,
    Delhi: 4,
    Punjab: 1,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "41": {
    Kerala: 15,
    Maharashtra: 5,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 1,
    Karnataka: 4,
    "Uttar Pradesh": 9,
    Ladakh: 3,
    "Tamil Nadu": 1,
    Telangana: 1,
    Rajasthan: 0,
    Haryana: 14,
    Delhi: 4,
    Punjab: 1,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "42": {
    Kerala: 17,
    Maharashtra: 10,
    "Andhra Pradesh": 0,
    "Jammu and Kashmir": 1,
    Karnataka: 4,
    "Uttar Pradesh": 10,
    Ladakh: 3,
    "Tamil Nadu": 1,
    Telangana: 1,
    Rajasthan: 1,
    Haryana: 14,
    Delhi: 5,
    Punjab: 1,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "43": {
    Kerala: 17,
    Maharashtra: 12,
    "Andhra Pradesh": 1,
    "Jammu and Kashmir": 1,
    Karnataka: 5,
    "Uttar Pradesh": 10,
    Ladakh: 3,
    "Tamil Nadu": 1,
    Telangana: 1,
    Rajasthan: 1,
    Haryana: 14,
    Delhi: 5,
    Punjab: 1,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "44": {
    Kerala: 19,
    Maharashtra: 14,
    "Andhra Pradesh": 1,
    "Jammu and Kashmir": 2,
    Karnataka: 6,
    "Uttar Pradesh": 11,
    Ladakh: 3,
    "Tamil Nadu": 1,
    Telangana: 1,
    Rajasthan: 1,
    Haryana: 14,
    Delhi: 7,
    Punjab: 1,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "45": {
    Kerala: 19,
    Maharashtra: 26,
    "Andhra Pradesh": 1,
    "Jammu and Kashmir": 2,
    Karnataka: 6,
    "Uttar Pradesh": 12,
    Ladakh: 3,
    "Tamil Nadu": 1,
    Telangana: 2,
    Rajasthan: 3,
    Haryana: 14,
    Delhi: 7,
    Punjab: 1,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "46": {
    Kerala: 22,
    Maharashtra: 31,
    "Andhra Pradesh": 1,
    "Jammu and Kashmir": 2,
    Karnataka: 6,
    "Uttar Pradesh": 12,
    Ladakh: 3,
    "Tamil Nadu": 1,
    Telangana: 2,
    Rajasthan: 4,
    Haryana: 14,
    Delhi: 7,
    Punjab: 1,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Odisha: 0,
    Puducherry: 0,
    Telangana: 0,
    Tripura: 0,
    Uttarakhand: 0,
    "West Bengal": 0,
  },
  "47": {
    "Andhra Pradesh": 1,
    Delhi: 7,
    Haryana: 14,
    Karnataka: 6,
    Kerala: 23,
    Maharashtra: 32,
    Odisha: 1,
    Punjab: 1,
    Rajasthan: 4,
    "Tamil Nadu": 1,
    Telangana: 3,
    "Jammu and Kashmir": 3,
    Ladakh: 4,
    "Uttar Pradesh": 13,
    Uttarakhand: 1,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Puducherry: 0,
    Tripura: 0,
    "West Bengal": 0,
  },
  "48": {
    "Andhra Pradesh": 1,
    Delhi: 8,
    Haryana: 15,
    Karnataka: 11,
    Kerala: 26,
    Maharashtra: 39,
    Odisha: 1,
    Punjab: 1,
    Rajasthan: 4,
    "Tamil Nadu": 1,
    Telangana: 5,
    "Jammu and Kashmir": 3,
    Ladakh: 6,
    "Uttar Pradesh": 15,
    Uttarakhand: 1,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Puducherry: 0,
    Tripura: 0,
    "West Bengal": 0,
  },
  "49": {
    "Andhra Pradesh": 1,
    Delhi: 10,
    Haryana: 17,
    Karnataka: 11,
    Kerala: 27,
    Maharashtra: 42,
    Odisha: 1,
    Puducherry: 1,
    Punjab: 1,
    Rajasthan: 4,
    "Tamil Nadu": 1,
    Telangana: 6,
    "Jammu and Kashmir": 3,
    Ladakh: 8,
    "Uttar Pradesh": 16,
    Uttarakhand: 1,
    "West Bengal": 1,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Chandigarh: 0,
    Chhattisgarh: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Tripura: 0,
  },
  "50": {
    "Andhra Pradesh": 2,
    Chhattisgarh: 1,
    Delhi: 12,
    Haryana: 17,
    Karnataka: 14,
    Kerala: 27,
    Maharashtra: 47,
    Odisha: 1,
    Puducherry: 1,
    Punjab: 2,
    Rajasthan: 7,
    "Tamil Nadu": 2,
    Telangana: 6,
    Chandigarh: 1,
    "Jammu and Kashmir": 4,
    Ladakh: 8,
    "Uttar Pradesh": 19,
    Uttarakhand: 1,
    "West Bengal": 1,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Goa: 0,
    Gujarat: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Tripura: 0,
  },
  "51": {
    "Andhra Pradesh": 3,
    Chhattisgarh: 1,
    Delhi: 17,
    Gujarat: 5,
    Haryana: 17,
    Karnataka: 15,
    Kerala: 28,
    Maharashtra: 52,
    Odisha: 2,
    Puducherry: 1,
    Punjab: 2,
    Rajasthan: 17,
    "Tamil Nadu": 3,
    Telangana: 17,
    Chandigarh: 1,
    "Jammu and Kashmir": 4,
    Ladakh: 10,
    "Uttar Pradesh": 23,
    Uttarakhand: 3,
    "West Bengal": 2,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Goa: 0,
    "Himachal Pradesh": 0,
    Jharkhand: 0,
    "Madhya Pradesh": 0,
    Manipur: 0,
    Mizoram: 0,
    Tripura: 0,
  },
  "52": {
    "Andhra Pradesh": 3,
    Chhattisgarh: 1,
    Delhi: 26,
    Gujarat: 7,
    Haryana: 17,
    "Himachal Pradesh": 2,
    Karnataka: 15,
    Kerala: 40,
    "Madhya Pradesh": 4,
    Maharashtra: 63,
    Odisha: 2,
    Puducherry: 1,
    Punjab: 13,
    Rajasthan: 17,
    "Tamil Nadu": 3,
    Telangana: 21,
    Chandigarh: 1,
    "Jammu and Kashmir": 4,
    Ladakh: 13,
    "Uttar Pradesh": 24,
    Uttarakhand: 3,
    "West Bengal": 3,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Bihar: 0,
    Goa: 0,
    Jharkhand: 0,
    Manipur: 0,
    Mizoram: 0,
    Tripura: 0,
  },
  "53": {
    "Andhra Pradesh": 5,
    Bihar: 2,
    Chhattisgarh: 1,
    Delhi: 29,
    Gujarat: 18,
    Haryana: 21,
    "Himachal Pradesh": 2,
    Karnataka: 26,
    Kerala: 52,
    "Madhya Pradesh": 4,
    Maharashtra: 67,
    Odisha: 2,
    Puducherry: 1,
    Punjab: 21,
    Rajasthan: 24,
    "Tamil Nadu": 7,
    Telangana: 22,
    Chandigarh: 5,
    "Jammu and Kashmir": 4,
    Ladakh: 13,
    "Uttar Pradesh": 27,
    Uttarakhand: 3,
    "West Bengal": 4,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Goa: 0,
    Jharkhand: 0,
    Manipur: 0,
    Mizoram: 0,
    Tripura: 0,
  },
  "54": {
    "Andhra Pradesh": 7,
    Bihar: 2,
    Chhattisgarh: 1,
    Delhi: 29,
    Gujarat: 29,
    Haryana: 26,
    "Himachal Pradesh": 2,
    Karnataka: 33,
    Kerala: 67,
    "Madhya Pradesh": 6,
    Maharashtra: 74,
    Odisha: 2,
    Puducherry: 1,
    Punjab: 21,
    Rajasthan: 28,
    "Tamil Nadu": 9,
    Telangana: 32,
    Chandigarh: 6,
    "Jammu and Kashmir": 4,
    Ladakh: 13,
    "Uttar Pradesh": 31,
    Uttarakhand: 3,
    "West Bengal": 7,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Goa: 0,
    Jharkhand: 0,
    Manipur: 0,
    Mizoram: 0,
    Tripura: 0,
  },
  "55": {
    "Andhra Pradesh": 8,
    Bihar: 3,
    Chhattisgarh: 1,
    Delhi: 30,
    Gujarat: 33,
    Haryana: 28,
    "Himachal Pradesh": 3,
    Karnataka: 37,
    Kerala: 95,
    "Madhya Pradesh": 7,
    Maharashtra: 89,
    Manipur: 1,
    Odisha: 2,
    Puducherry: 1,
    Punjab: 29,
    Rajasthan: 32,
    "Tamil Nadu": 15,
    Telangana: 35,
    Chandigarh: 7,
    "Jammu and Kashmir": 4,
    Ladakh: 13,
    "Uttar Pradesh": 33,
    Uttarakhand: 4,
    "West Bengal": 9,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Goa: 0,
    Jharkhand: 0,
    Mizoram: 0,
    Tripura: 0,
  },
  "56": {
    "Andhra Pradesh": 9,
    Bihar: 4,
    Chhattisgarh: 1,
    Delhi: 31,
    Gujarat: 38,
    Haryana: 28,
    "Himachal Pradesh": 3,
    Karnataka: 41,
    Kerala: 109,
    "Madhya Pradesh": 14,
    Maharashtra: 128,
    Manipur: 1,
    Mizoram: 1,
    Odisha: 2,
    Puducherry: 1,
    Punjab: 29,
    Rajasthan: 36,
    "Tamil Nadu": 18,
    Telangana: 35,
    Chandigarh: 7,
    "Jammu and Kashmir": 7,
    Ladakh: 13,
    "Uttar Pradesh": 37,
    Uttarakhand: 4,
    "West Bengal": 9,
    "Andaman and Nicobar Islands": 0,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Goa: 0,
    Jharkhand: 0,
    Tripura: 0,
  },
  "57": {
    "Andaman and Nicobar Islands": 1,
    "Andhra Pradesh": 11,
    Bihar: 6,
    Chandigarh: 7,
    Chhattisgarh: 6,
    Delhi: 36,
    Goa: 3,
    Gujarat: 43,
    Haryana: 30,
    "Himachal Pradesh": 3,
    "Jammu and Kashmir": 13,
    Karnataka: 55,
    Kerala: 118,
    Ladakh: 13,
    "Madhya Pradesh": 20,
    Maharashtra: 124,
    Manipur: 1,
    Mizoram: 1,
    Odisha: 2,
    Puducherry: 1,
    Punjab: 33,
    Rajasthan: 41,
    "Tamil Nadu": 26,
    Telangana: 44,
    Uttarakhand: 5,
    "Uttar Pradesh": 41,
    "West Bengal": 10,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Jharkhand: 0,
    Tripura: 0,
  },
  "58": {
    "Andaman and Nicobar Islands": 1,
    "Andhra Pradesh": 12,
    Bihar: 6,
    Chandigarh: 7,
    Chhattisgarh: 6,
    Delhi: 36,
    Goa: 3,
    Gujarat: 43,
    Haryana: 30,
    "Himachal Pradesh": 3,
    "Jammu and Kashmir": 13,
    Karnataka: 55,
    Kerala: 137,
    Ladakh: 13,
    "Madhya Pradesh": 20,
    Maharashtra: 130,
    Manipur: 1,
    Mizoram: 1,
    Odisha: 2,
    Puducherry: 1,
    Punjab: 33,
    Rajasthan: 41,
    "Tamil Nadu": 29,
    Telangana: 45,
    Uttarakhand: 5,
    "Uttar Pradesh": 41,
    "West Bengal": 10,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Jharkhand: 0,
    Tripura: 0,
  },
  "59": {
    "Andhra Pradesh": 14,
    "Andaman and Nicobar Islands": 6,
    Bihar: 9,
    Chandigarh: 8,
    Chhattisgarh: 6,
    Delhi: 39,
    Goa: 3,
    Gujarat: 45,
    Haryana: 33,
    "Himachal Pradesh": 3,
    "Jammu and Kashmir": 20,
    Karnataka: 55,
    Kerala: 176,
    Ladakh: 13,
    "Madhya Pradesh": 30,
    Maharashtra: 180,
    Manipur: 1,
    Mizoram: 1,
    Odisha: 3,
    Puducherry: 1,
    Punjab: 38,
    Rajasthan: 54,
    "Tamil Nadu": 40,
    Telangana: 56,
    Uttarakhand: 5,
    "Uttar Pradesh": 55,
    "West Bengal": 15,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Jharkhand: 0,
    Tripura: 0,
  },
  "60": {
    "Andhra Pradesh": 19,
    "Andaman and Nicobar Islands": 9,
    Bihar: 11,
    Chandigarh: 8,
    Chhattisgarh: 7,
    Delhi: 49,
    Goa: 5,
    Gujarat: 58,
    Haryana: 33,
    "Himachal Pradesh": 3,
    "Jammu and Kashmir": 31,
    Karnataka: 76,
    Kerala: 182,
    Ladakh: 13,
    "Madhya Pradesh": 30,
    Maharashtra: 186,
    Manipur: 1,
    Mizoram: 1,
    Odisha: 3,
    Puducherry: 1,
    Punjab: 38,
    Rajasthan: 55,
    "Tamil Nadu": 49,
    Telangana: 66,
    Uttarakhand: 7,
    "Uttar Pradesh": 65,
    "West Bengal": 18,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Jharkhand: 0,
    Tripura: 0,
  },
  "61": {
    "Andhra Pradesh": 23,
    "Andaman and Nicobar Islands": 9,
    Bihar: 15,
    Chandigarh: 8,
    Chhattisgarh: 7,
    Delhi: 87,
    Goa: 5,
    Gujarat: 69,
    Haryana: 36,
    "Himachal Pradesh": 3,
    "Jammu and Kashmir": 48,
    Karnataka: 83,
    Kerala: 202,
    Ladakh: 13,
    "Madhya Pradesh": 47,
    Maharashtra: 198,
    Manipur: 1,
    Mizoram: 1,
    Odisha: 3,
    Puducherry: 1,
    Punjab: 38,
    Rajasthan: 59,
    "Tamil Nadu": 67,
    Telangana: 71,
    Uttarakhand: 7,
    "Uttar Pradesh": 82,
    "West Bengal": 22,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Jharkhand: 0,
    Tripura: 0,
  },
  "62": {
    "Andhra Pradesh": 40,
    "Andaman and Nicobar Islands": 10,
    Bihar: 15,
    Chandigarh: 13,
    Chhattisgarh: 8,
    Delhi: 97,
    Goa: 5,
    Gujarat: 73,
    Haryana: 40,
    "Himachal Pradesh": 3,
    "Jammu and Kashmir": 54,
    Karnataka: 83,
    Kerala: 234,
    Ladakh: 13,
    "Madhya Pradesh": 47,
    Maharashtra: 216,
    Manipur: 1,
    Mizoram: 1,
    Odisha: 3,
    Puducherry: 1,
    Punjab: 41,
    Rajasthan: 74,
    "Tamil Nadu": 74,
    Telangana: 79,
    Uttarakhand: 7,
    "Uttar Pradesh": 101,
    "West Bengal": 26,
    "Arunachal Pradesh": 0,
    Assam: 0,
    Jharkhand: 0,
    Tripura: 0,
  },
  "63": {
    "Andhra Pradesh": 83,
    "Andaman and Nicobar Islands": 10,
    Assam: 1,
    Bihar: 23,
    Chandigarh: 16,
    Chhattisgarh: 9,
    Delhi: 152,
    Goa: 5,
    Gujarat: 82,
    Haryana: 43,
    "Himachal Pradesh": 3,
    "Jammu and Kashmir": 62,
    Jharkhand: 1,
    Karnataka: 101,
    Kerala: 241,
    Ladakh: 13,
    "Madhya Pradesh": 66,
    Maharashtra: 302,
    Manipur: 1,
    Mizoram: 1,
    Odisha: 4,
    Puducherry: 3,
    Punjab: 42,
    Rajasthan: 93,
    "Tamil Nadu": 234,
    Telangana: 96,
    Uttarakhand: 7,
    "Uttar Pradesh": 103,
    "West Bengal": 37,
    "Arunachal Pradesh": 0,
    Tripura: 0,
  },
  "64": {
    "Andhra Pradesh": 86,
    "Andaman and Nicobar Islands": 10,
    Assam: 5,
    Bihar: 24,
    Chandigarh: 16,
    Chhattisgarh: 9,
    Delhi: 219,
    Goa: 5,
    Gujarat: 87,
    Haryana: 43,
    "Himachal Pradesh": 3,
    "Jammu and Kashmir": 62,
    Jharkhand: 1,
    Karnataka: 110,
    Kerala: 265,
    Ladakh: 13,
    "Madhya Pradesh": 99,
    Maharashtra: 335,
    Manipur: 1,
    Mizoram: 1,
    Odisha: 4,
    Puducherry: 3,
    Punjab: 46,
    Rajasthan: 108,
    "Tamil Nadu": 234,
    Telangana: 107,
    Uttarakhand: 7,
    "Uttar Pradesh": 113,
    "West Bengal": 53,
    "Arunachal Pradesh": 0,
    Tripura: 0,
  },
  "65": {
    "Andhra Pradesh": 132,
    "Andaman and Nicobar Islands": 10,
    "Arunachal Pradesh": 1,
    Assam: 16,
    Bihar: 29,
    Chandigarh: 18,
    Chhattisgarh: 9,
    Delhi: 219,
    Goa: 6,
    Gujarat: 95,
    Haryana: 49,
    "Himachal Pradesh": 6,
    "Jammu and Kashmir": 75,
    Jharkhand: 2,
    Karnataka: 124,
    Kerala: 286,
    Ladakh: 14,
    "Madhya Pradesh": 104,
    Maharashtra: 335,
    Manipur: 2,
    Mizoram: 1,
    Odisha: 5,
    Puducherry: 5,
    Punjab: 48,
    Rajasthan: 167,
    "Tamil Nadu": 309,
    Telangana: 158,
    Uttarakhand: 10,
    "Uttar Pradesh": 172,
    "West Bengal": 63,
    Tripura: 0,
  },
  "66": {
    "Andhra Pradesh": 161,
    "Andaman and Nicobar Islands": 10,
    "Arunachal Pradesh": 1,
    Assam: 24,
    Bihar: 30,
    Chandigarh: 18,
    Chhattisgarh: 9,
    Delhi: 445,
    Goa: 7,
    Gujarat: 105,
    Haryana: 49,
    "Himachal Pradesh": 6,
    "Jammu and Kashmir": 75,
    Jharkhand: 2,
    Karnataka: 128,
    Kerala: 295,
    Ladakh: 14,
    "Madhya Pradesh": 104,
    Maharashtra: 490,
    Manipur: 2,
    Mizoram: 1,
    Odisha: 5,
    Puducherry: 5,
    Punjab: 57,
    Rajasthan: 200,
    "Tamil Nadu": 411,
    Telangana: 159,
    Uttarakhand: 16,
    "Uttar Pradesh": 174,
    "West Bengal": 69,
    Tripura: 0,
  },
  "67": {
    "Andhra Pradesh": 190,
    "Andaman and Nicobar Islands": 10,
    "Arunachal Pradesh": 1,
    Assam: 26,
    Bihar: 30,
    Chandigarh: 18,
    Chhattisgarh: 9,
    Delhi: 503,
    Goa: 7,
    Gujarat: 122,
    Haryana: 59,
    "Himachal Pradesh": 6,
    "Jammu and Kashmir": 106,
    Jharkhand: 3,
    Karnataka: 144,
    Kerala: 306,
    Ladakh: 14,
    "Madhya Pradesh": 165,
    Maharashtra: 490,
    Manipur: 2,
    Mizoram: 1,
    Odisha: 20,
    Puducherry: 5,
    Punjab: 57,
    Rajasthan: 200,
    "Tamil Nadu": 485,
    Telangana: 269,
    Uttarakhand: 22,
    "Uttar Pradesh": 227,
    "West Bengal": 80,
    Tripura: 0,
  },
  "68": {
    "Andhra Pradesh": 226,
    "Andaman and Nicobar Islands": 10,
    "Arunachal Pradesh": 1,
    Assam: 26,
    Bihar: 32,
    Chandigarh: 18,
    Chhattisgarh: 10,
    Delhi: 523,
    Goa: 7,
    Gujarat: 144,
    Haryana: 84,
    "Himachal Pradesh": 13,
    "Jammu and Kashmir": 109,
    Jharkhand: 4,
    Karnataka: 151,
    Kerala: 314,
    Ladakh: 14,
    "Madhya Pradesh": 165,
    Maharashtra: 748,
    Manipur: 2,
    Mizoram: 1,
    Odisha: 21,
    Puducherry: 5,
    Punjab: 76,
    Rajasthan: 274,
    "Tamil Nadu": 571,
    Telangana: 321,
    Uttarakhand: 26,
    "Uttar Pradesh": 305,
    "West Bengal": 80,
    Tripura: 0,
  },
  "69": {
    "Andhra Pradesh": 266,
    "Andaman and Nicobar Islands": 10,
    "Arunachal Pradesh": 1,
    Assam: 26,
    Bihar: 32,
    Chandigarh: 18,
    Chhattisgarh: 10,
    Delhi: 576,
    Goa: 7,
    Gujarat: 165,
    Haryana: 90,
    "Himachal Pradesh": 13,
    "Jammu and Kashmir": 116,
    Jharkhand: 4,
    Karnataka: 175,
    Kerala: 327,
    Ladakh: 14,
    "Madhya Pradesh": 229,
    Maharashtra: 868,
    Manipur: 2,
    Mizoram: 1,
    Odisha: 42,
    Puducherry: 5,
    Punjab: 91,
    Rajasthan: 288,
    "Tamil Nadu": 621,
    Telangana: 364,
    Tripura: 1,
    Uttarakhand: 31,
    "Uttar Pradesh": 305,
    "West Bengal": 91,
  },
  "70": {
    "Andhra Pradesh": 305,
    "Andaman and Nicobar Islands": 10,
    "Arunachal Pradesh": 1,
    Assam: 27,
    Bihar: 38,
    Chandigarh: 18,
    Chhattisgarh: 10,
    Delhi: 576,
    Goa: 7,
    Gujarat: 165,
    Haryana: 147,
    "Himachal Pradesh": 18,
    "Jammu and Kashmir": 116,
    Jharkhand: 4,
    Karnataka: 175,
    Kerala: 336,
    Ladakh: 14,
    "Madhya Pradesh": 229,
    Maharashtra: 1018,
    Manipur: 2,
    Mizoram: 1,
    Odisha: 42,
    Puducherry: 5,
    Punjab: 91,
    Rajasthan: 328,
    "Tamil Nadu": 690,
    Telangana: 427,
    Tripura: 1,
    Uttarakhand: 31,
    "Uttar Pradesh": 343,
    "West Bengal": 99,
  },
  "71": {
    "Andhra Pradesh": 348,
    "Andaman and Nicobar Islands": 11,
    "Arunachal Pradesh": 1,
    Assam: 28,
    Bihar: 39,
    Chandigarh: 18,
    Chhattisgarh: 10,
    Delhi: 669,
    Goa: 7,
    Gujarat: 179,
    Haryana: 169,
    "Himachal Pradesh": 18,
    "Jammu and Kashmir": 158,
    Jharkhand: 13,
    Karnataka: 181,
    Kerala: 345,
    Ladakh: 14,
    "Madhya Pradesh": 259,
    Maharashtra: 1135,
    Manipur: 2,
    Mizoram: 1,
    Odisha: 42,
    Puducherry: 5,
    Punjab: 101,
    Rajasthan: 383,
    "Tamil Nadu": 738,
    Telangana: 442,
    Tripura: 1,
    Uttarakhand: 35,
    "Uttar Pradesh": 410,
    "West Bengal": 103,
  },
  "72": {
    "Andhra Pradesh": 363,
    "Andaman and Nicobar Islands": 11,
    "Arunachal Pradesh": 1,
    Assam: 29,
    Bihar: 60,
    Chandigarh: 18,
    Chhattisgarh: 10,
    Delhi: 898,
    Goa: 7,
    Gujarat: 241,
    Haryana: 169,
    "Himachal Pradesh": 28,
    "Jammu and Kashmir": 184,
    Jharkhand: 13,
    Karnataka: 197,
    Kerala: 357,
    Ladakh: 15,
    "Madhya Pradesh": 259,
    Maharashtra: 1364,
    Manipur: 2,
    Mizoram: 1,
    Odisha: 44,
    Puducherry: 5,
    Punjab: 132,
    Rajasthan: 463,
    "Tamil Nadu": 834,
    Telangana: 473,
    Tripura: 1,
    Uttarakhand: 35,
    "Uttar Pradesh": 431,
    "West Bengal": 116,
  },
  "73": {
    "Andhra Pradesh": 363,
    "Andaman and Nicobar Islands": 11,
    "Arunachal Pradesh": 1,
    Assam: 29,
    Bihar: 60,
    Chandigarh: 18,
    Chhattisgarh: 18,
    Delhi: 903,
    Goa: 7,
    Gujarat: 308,
    Haryana: 177,
    "Himachal Pradesh": 28,
    "Jammu and Kashmir": 207,
    Jharkhand: 14,
    Karnataka: 207,
    Kerala: 364,
    Ladakh: 15,
    "Madhya Pradesh": 435,
    Maharashtra: 1574,
    Manipur: 2,
    Mizoram: 1,
    Odisha: 48,
    Puducherry: 5,
    Punjab: 132,
    Rajasthan: 553,
    "Tamil Nadu": 911,
    Telangana: 473,
    Tripura: 1,
    Uttarakhand: 35,
    "Uttar Pradesh": 431,
    "West Bengal": 116,
  },
};
const kimoji = Object.values({
  AC: {
    unicode: "U+1F1E6 U+1F1E8",
    name: "Ascension Island",
    emoji: "🇦🇨",
  },
  AD: {
    unicode: "U+1F1E6 U+1F1E9",
    name: "Andorra",
    emoji: "🇦🇩",
  },
  AE: {
    unicode: "U+1F1E6 U+1F1EA",
    name: "United Arab Emirates",
    emoji: "🇦🇪",
  },
  AF: {
    unicode: "U+1F1E6 U+1F1EB",
    name: "Afghanistan",
    emoji: "🇦🇫",
  },
  AG: {
    unicode: "U+1F1E6 U+1F1EC",
    name: "Antigua & Barbuda",
    emoji: "🇦🇬",
  },
  AI: {
    unicode: "U+1F1E6 U+1F1EE",
    name: "Anguilla",
    emoji: "🇦🇮",
  },
  AL: {
    unicode: "U+1F1E6 U+1F1F1",
    name: "Albania",
    emoji: "🇦🇱",
  },
  AM: {
    unicode: "U+1F1E6 U+1F1F2",
    name: "Armenia",
    emoji: "🇦🇲",
  },
  AO: {
    unicode: "U+1F1E6 U+1F1F4",
    name: "Angola",
    emoji: "🇦🇴",
  },
  AQ: {
    unicode: "U+1F1E6 U+1F1F6",
    name: "Antarctica",
    emoji: "🇦🇶",
  },
  AR: {
    unicode: "U+1F1E6 U+1F1F7",
    name: "Argentina",
    emoji: "🇦🇷",
  },
  AS: {
    unicode: "U+1F1E6 U+1F1F8",
    name: "American Samoa",
    emoji: "🇦🇸",
  },
  AT: {
    unicode: "U+1F1E6 U+1F1F9",
    name: "Austria",
    emoji: "🇦🇹",
  },
  AU: {
    unicode: "U+1F1E6 U+1F1FA",
    name: "Australia",
    emoji: "🇦🇺",
  },
  AW: {
    unicode: "U+1F1E6 U+1F1FC",
    name: "Aruba",
    emoji: "🇦🇼",
  },
  AX: {
    unicode: "U+1F1E6 U+1F1FD",
    name: "Åland Islands",
    emoji: "🇦🇽",
  },
  AZ: {
    unicode: "U+1F1E6 U+1F1FF",
    name: "Azerbaijan",
    emoji: "🇦🇿",
  },
  BA: {
    unicode: "U+1F1E7 U+1F1E6",
    name: "Bosnia & Herzegovina",
    emoji: "🇧🇦",
  },
  BB: {
    unicode: "U+1F1E7 U+1F1E7",
    name: "Barbados",
    emoji: "🇧🇧",
  },
  BD: {
    unicode: "U+1F1E7 U+1F1E9",
    name: "Bangladesh",
    emoji: "🇧🇩",
  },
  BE: {
    unicode: "U+1F1E7 U+1F1EA",
    name: "Belgium",
    emoji: "🇧🇪",
  },
  BF: {
    unicode: "U+1F1E7 U+1F1EB",
    name: "Burkina Faso",
    emoji: "🇧🇫",
  },
  BG: {
    unicode: "U+1F1E7 U+1F1EC",
    name: "Bulgaria",
    emoji: "🇧🇬",
  },
  BH: {
    unicode: "U+1F1E7 U+1F1ED",
    name: "Bahrain",
    emoji: "🇧🇭",
  },
  BI: {
    unicode: "U+1F1E7 U+1F1EE",
    name: "Burundi",
    emoji: "🇧🇮",
  },
  BJ: {
    unicode: "U+1F1E7 U+1F1EF",
    name: "Benin",
    emoji: "🇧🇯",
  },
  BL: {
    unicode: "U+1F1E7 U+1F1F1",
    name: "St. Barthélemy",
    emoji: "🇧🇱",
  },
  BM: {
    unicode: "U+1F1E7 U+1F1F2",
    name: "Bermuda",
    emoji: "🇧🇲",
  },
  BN: {
    unicode: "U+1F1E7 U+1F1F3",
    name: "Brunei",
    emoji: "🇧🇳",
  },
  BO: {
    unicode: "U+1F1E7 U+1F1F4",
    name: "Bolivia",
    emoji: "🇧🇴",
  },
  BQ: {
    unicode: "U+1F1E7 U+1F1F6",
    name: "Caribbean Netherlands",
    emoji: "🇧🇶",
  },
  BR: {
    unicode: "U+1F1E7 U+1F1F7",
    name: "Brazil",
    emoji: "🇧🇷",
  },
  BS: {
    unicode: "U+1F1E7 U+1F1F8",
    name: "Bahamas",
    emoji: "🇧🇸",
  },
  BT: {
    unicode: "U+1F1E7 U+1F1F9",
    name: "Bhutan",
    emoji: "🇧🇹",
  },
  BV: {
    unicode: "U+1F1E7 U+1F1FB",
    name: "Bouvet Island",
    emoji: "🇧🇻",
  },
  BW: {
    unicode: "U+1F1E7 U+1F1FC",
    name: "Botswana",
    emoji: "🇧🇼",
  },
  BY: {
    unicode: "U+1F1E7 U+1F1FE",
    name: "Belarus",
    emoji: "🇧🇾",
  },
  BZ: {
    unicode: "U+1F1E7 U+1F1FF",
    name: "Belize",
    emoji: "🇧🇿",
  },
  CA: {
    unicode: "U+1F1E8 U+1F1E6",
    name: "Canada",
    emoji: "🇨🇦",
  },
  CC: {
    unicode: "U+1F1E8 U+1F1E8",
    name: "Cocos (Keeling) Islands",
    emoji: "🇨🇨",
  },
  CD: {
    unicode: "U+1F1E8 U+1F1E9",
    name: "Congo - Kinshasa",
    emoji: "🇨🇩",
  },
  CF: {
    unicode: "U+1F1E8 U+1F1EB",
    name: "Central African Republic",
    emoji: "🇨🇫",
  },
  CG: {
    unicode: "U+1F1E8 U+1F1EC",
    name: "Congo - Brazzaville",
    emoji: "🇨🇬",
  },
  CH: {
    unicode: "U+1F1E8 U+1F1ED",
    name: "Switzerland",
    emoji: "🇨🇭",
  },
  CI: {
    unicode: "U+1F1E8 U+1F1EE",
    name: "Côte d’Ivoire",
    emoji: "🇨🇮",
  },
  CK: {
    unicode: "U+1F1E8 U+1F1F0",
    name: "Cook Islands",
    emoji: "🇨🇰",
  },
  CL: {
    unicode: "U+1F1E8 U+1F1F1",
    name: "Chile",
    emoji: "🇨🇱",
  },
  CM: {
    unicode: "U+1F1E8 U+1F1F2",
    name: "Cameroon",
    emoji: "🇨🇲",
  },
  CN: {
    unicode: "U+1F1E8 U+1F1F3",
    name: "China",
    emoji: "🇨🇳",
  },
  CO: {
    unicode: "U+1F1E8 U+1F1F4",
    name: "Colombia",
    emoji: "🇨🇴",
  },
  CP: {
    unicode: "U+1F1E8 U+1F1F5",
    name: "Clipperton Island",
    emoji: "🇨🇵",
  },
  CR: {
    unicode: "U+1F1E8 U+1F1F7",
    name: "Costa Rica",
    emoji: "🇨🇷",
  },
  CU: {
    unicode: "U+1F1E8 U+1F1FA",
    name: "Cuba",
    emoji: "🇨🇺",
  },
  CV: {
    unicode: "U+1F1E8 U+1F1FB",
    name: "Cape Verde",
    emoji: "🇨🇻",
  },
  CW: {
    unicode: "U+1F1E8 U+1F1FC",
    name: "Curaçao",
    emoji: "🇨🇼",
  },
  CX: {
    unicode: "U+1F1E8 U+1F1FD",
    name: "Christmas Island",
    emoji: "🇨🇽",
  },
  CY: {
    unicode: "U+1F1E8 U+1F1FE",
    name: "Cyprus",
    emoji: "🇨🇾",
  },
  CZ: {
    unicode: "U+1F1E8 U+1F1FF",
    name: "Czechia",
    emoji: "🇨🇿",
  },
  DE: {
    unicode: "U+1F1E9 U+1F1EA",
    name: "Germany",
    emoji: "🇩🇪",
  },
  DG: {
    unicode: "U+1F1E9 U+1F1EC",
    name: "Diego Garcia",
    emoji: "🇩🇬",
  },
  DJ: {
    unicode: "U+1F1E9 U+1F1EF",
    name: "Djibouti",
    emoji: "🇩🇯",
  },
  DK: {
    unicode: "U+1F1E9 U+1F1F0",
    name: "Denmark",
    emoji: "🇩🇰",
  },
  DM: {
    unicode: "U+1F1E9 U+1F1F2",
    name: "Dominica",
    emoji: "🇩🇲",
  },
  DO: {
    unicode: "U+1F1E9 U+1F1F4",
    name: "Dominican Republic",
    emoji: "🇩🇴",
  },
  DZ: {
    unicode: "U+1F1E9 U+1F1FF",
    name: "Algeria",
    emoji: "🇩🇿",
  },
  EA: {
    unicode: "U+1F1EA U+1F1E6",
    name: "Ceuta & Melilla",
    emoji: "🇪🇦",
  },
  EC: {
    unicode: "U+1F1EA U+1F1E8",
    name: "Ecuador",
    emoji: "🇪🇨",
  },
  EE: {
    unicode: "U+1F1EA U+1F1EA",
    name: "Estonia",
    emoji: "🇪🇪",
  },
  EG: {
    unicode: "U+1F1EA U+1F1EC",
    name: "Egypt",
    emoji: "🇪🇬",
  },
  EH: {
    unicode: "U+1F1EA U+1F1ED",
    name: "Western Sahara",
    emoji: "🇪🇭",
  },
  ER: {
    unicode: "U+1F1EA U+1F1F7",
    name: "Eritrea",
    emoji: "🇪🇷",
  },
  ES: {
    unicode: "U+1F1EA U+1F1F8",
    name: "Spain",
    emoji: "🇪🇸",
  },
  ET: {
    unicode: "U+1F1EA U+1F1F9",
    name: "Ethiopia",
    emoji: "🇪🇹",
  },
  EU: {
    unicode: "U+1F1EA U+1F1FA",
    name: "European Union",
    emoji: "🇪🇺",
  },
  FI: {
    unicode: "U+1F1EB U+1F1EE",
    name: "Finland",
    emoji: "🇫🇮",
  },
  FJ: {
    unicode: "U+1F1EB U+1F1EF",
    name: "Fiji",
    emoji: "🇫🇯",
  },
  FK: {
    unicode: "U+1F1EB U+1F1F0",
    name: "Falkland Islands",
    emoji: "🇫🇰",
  },
  FM: {
    unicode: "U+1F1EB U+1F1F2",
    name: "Micronesia",
    emoji: "🇫🇲",
  },
  FO: {
    unicode: "U+1F1EB U+1F1F4",
    name: "Faroe Islands",
    emoji: "🇫🇴",
  },
  FR: {
    unicode: "U+1F1EB U+1F1F7",
    name: "France",
    emoji: "🇫🇷",
  },
  GA: {
    unicode: "U+1F1EC U+1F1E6",
    name: "Gabon",
    emoji: "🇬🇦",
  },
  GB: {
    unicode: "U+1F1EC U+1F1E7",
    name: "United Kingdom",
    emoji: "🇬🇧",
  },
  GD: {
    unicode: "U+1F1EC U+1F1E9",
    name: "Grenada",
    emoji: "🇬🇩",
  },
  GE: {
    unicode: "U+1F1EC U+1F1EA",
    name: "Georgia",
    emoji: "🇬🇪",
  },
  GF: {
    unicode: "U+1F1EC U+1F1EB",
    name: "French Guiana",
    emoji: "🇬🇫",
  },
  GG: {
    unicode: "U+1F1EC U+1F1EC",
    name: "Guernsey",
    emoji: "🇬🇬",
  },
  GH: {
    unicode: "U+1F1EC U+1F1ED",
    name: "Ghana",
    emoji: "🇬🇭",
  },
  GI: {
    unicode: "U+1F1EC U+1F1EE",
    name: "Gibraltar",
    emoji: "🇬🇮",
  },
  GL: {
    unicode: "U+1F1EC U+1F1F1",
    name: "Greenland",
    emoji: "🇬🇱",
  },
  GM: {
    unicode: "U+1F1EC U+1F1F2",
    name: "Gambia",
    emoji: "🇬🇲",
  },
  GN: {
    unicode: "U+1F1EC U+1F1F3",
    name: "Guinea",
    emoji: "🇬🇳",
  },
  GP: {
    unicode: "U+1F1EC U+1F1F5",
    name: "Guadeloupe",
    emoji: "🇬🇵",
  },
  GQ: {
    unicode: "U+1F1EC U+1F1F6",
    name: "Equatorial Guinea",
    emoji: "🇬🇶",
  },
  GR: {
    unicode: "U+1F1EC U+1F1F7",
    name: "Greece",
    emoji: "🇬🇷",
  },
  GS: {
    unicode: "U+1F1EC U+1F1F8",
    name: "South Georgia & South Sandwich Islands",
    emoji: "🇬🇸",
  },
  GT: {
    unicode: "U+1F1EC U+1F1F9",
    name: "Guatemala",
    emoji: "🇬🇹",
  },
  GU: {
    unicode: "U+1F1EC U+1F1FA",
    name: "Guam",
    emoji: "🇬🇺",
  },
  GW: {
    unicode: "U+1F1EC U+1F1FC",
    name: "Guinea-Bissau",
    emoji: "🇬🇼",
  },
  GY: {
    unicode: "U+1F1EC U+1F1FE",
    name: "Guyana",
    emoji: "🇬🇾",
  },
  HK: {
    unicode: "U+1F1ED U+1F1F0",
    name: "Hong Kong SAR China",
    emoji: "🇭🇰",
  },
  HM: {
    unicode: "U+1F1ED U+1F1F2",
    name: "Heard & McDonald Islands",
    emoji: "🇭🇲",
  },
  HN: {
    unicode: "U+1F1ED U+1F1F3",
    name: "Honduras",
    emoji: "🇭🇳",
  },
  HR: {
    unicode: "U+1F1ED U+1F1F7",
    name: "Croatia",
    emoji: "🇭🇷",
  },
  HT: {
    unicode: "U+1F1ED U+1F1F9",
    name: "Haiti",
    emoji: "🇭🇹",
  },
  HU: {
    unicode: "U+1F1ED U+1F1FA",
    name: "Hungary",
    emoji: "🇭🇺",
  },
  IC: {
    unicode: "U+1F1EE U+1F1E8",
    name: "Canary Islands",
    emoji: "🇮🇨",
  },
  ID: {
    unicode: "U+1F1EE U+1F1E9",
    name: "Indonesia",
    emoji: "🇮🇩",
  },
  IE: {
    unicode: "U+1F1EE U+1F1EA",
    name: "Ireland",
    emoji: "🇮🇪",
  },
  IL: {
    unicode: "U+1F1EE U+1F1F1",
    name: "Israel",
    emoji: "🇮🇱",
  },
  IM: {
    unicode: "U+1F1EE U+1F1F2",
    name: "Isle of Man",
    emoji: "🇮🇲",
  },
  IN: {
    unicode: "U+1F1EE U+1F1F3",
    name: "India",
    emoji: "🇮🇳",
  },
  IO: {
    unicode: "U+1F1EE U+1F1F4",
    name: "British Indian Ocean Territory",
    emoji: "🇮🇴",
  },
  IQ: {
    unicode: "U+1F1EE U+1F1F6",
    name: "Iraq",
    emoji: "🇮🇶",
  },
  IR: {
    unicode: "U+1F1EE U+1F1F7",
    name: "Iran",
    emoji: "🇮🇷",
  },
  IS: {
    unicode: "U+1F1EE U+1F1F8",
    name: "Iceland",
    emoji: "🇮🇸",
  },
  IT: {
    unicode: "U+1F1EE U+1F1F9",
    name: "Italy",
    emoji: "🇮🇹",
  },
  JE: {
    unicode: "U+1F1EF U+1F1EA",
    name: "Jersey",
    emoji: "🇯🇪",
  },
  JM: {
    unicode: "U+1F1EF U+1F1F2",
    name: "Jamaica",
    emoji: "🇯🇲",
  },
  JO: {
    unicode: "U+1F1EF U+1F1F4",
    name: "Jordan",
    emoji: "🇯🇴",
  },
  JP: {
    unicode: "U+1F1EF U+1F1F5",
    name: "Japan",
    emoji: "🇯🇵",
  },
  KE: {
    unicode: "U+1F1F0 U+1F1EA",
    name: "Kenya",
    emoji: "🇰🇪",
  },
  KG: {
    unicode: "U+1F1F0 U+1F1EC",
    name: "Kyrgyzstan",
    emoji: "🇰🇬",
  },
  KH: {
    unicode: "U+1F1F0 U+1F1ED",
    name: "Cambodia",
    emoji: "🇰🇭",
  },
  KI: {
    unicode: "U+1F1F0 U+1F1EE",
    name: "Kiribati",
    emoji: "🇰🇮",
  },
  KM: {
    unicode: "U+1F1F0 U+1F1F2",
    name: "Comoros",
    emoji: "🇰🇲",
  },
  KN: {
    unicode: "U+1F1F0 U+1F1F3",
    name: "St. Kitts & Nevis",
    emoji: "🇰🇳",
  },
  KP: {
    unicode: "U+1F1F0 U+1F1F5",
    name: "North Korea",
    emoji: "🇰🇵",
  },
  KR: {
    unicode: "U+1F1F0 U+1F1F7",
    name: "South Korea",
    emoji: "🇰🇷",
  },
  KW: {
    unicode: "U+1F1F0 U+1F1FC",
    name: "Kuwait",
    emoji: "🇰🇼",
  },
  KY: {
    unicode: "U+1F1F0 U+1F1FE",
    name: "Cayman Islands",
    emoji: "🇰🇾",
  },
  KZ: {
    unicode: "U+1F1F0 U+1F1FF",
    name: "Kazakhstan",
    emoji: "🇰🇿",
  },
  LA: {
    unicode: "U+1F1F1 U+1F1E6",
    name: "Laos",
    emoji: "🇱🇦",
  },
  LB: {
    unicode: "U+1F1F1 U+1F1E7",
    name: "Lebanon",
    emoji: "🇱🇧",
  },
  LC: {
    unicode: "U+1F1F1 U+1F1E8",
    name: "St. Lucia",
    emoji: "🇱🇨",
  },
  LI: {
    unicode: "U+1F1F1 U+1F1EE",
    name: "Liechtenstein",
    emoji: "🇱🇮",
  },
  LK: {
    unicode: "U+1F1F1 U+1F1F0",
    name: "Sri Lanka",
    emoji: "🇱🇰",
  },
  LR: {
    unicode: "U+1F1F1 U+1F1F7",
    name: "Liberia",
    emoji: "🇱🇷",
  },
  LS: {
    unicode: "U+1F1F1 U+1F1F8",
    name: "Lesotho",
    emoji: "🇱🇸",
  },
  LT: {
    unicode: "U+1F1F1 U+1F1F9",
    name: "Lithuania",
    emoji: "🇱🇹",
  },
  LU: {
    unicode: "U+1F1F1 U+1F1FA",
    name: "Luxembourg",
    emoji: "🇱🇺",
  },
  LV: {
    unicode: "U+1F1F1 U+1F1FB",
    name: "Latvia",
    emoji: "🇱🇻",
  },
  LY: {
    unicode: "U+1F1F1 U+1F1FE",
    name: "Libya",
    emoji: "🇱🇾",
  },
  MA: {
    unicode: "U+1F1F2 U+1F1E6",
    name: "Morocco",
    emoji: "🇲🇦",
  },
  MC: {
    unicode: "U+1F1F2 U+1F1E8",
    name: "Monaco",
    emoji: "🇲🇨",
  },
  MD: {
    unicode: "U+1F1F2 U+1F1E9",
    name: "Moldova",
    emoji: "🇲🇩",
  },
  ME: {
    unicode: "U+1F1F2 U+1F1EA",
    name: "Montenegro",
    emoji: "🇲🇪",
  },
  MF: {
    unicode: "U+1F1F2 U+1F1EB",
    name: "St. Martin",
    emoji: "🇲🇫",
  },
  MG: {
    unicode: "U+1F1F2 U+1F1EC",
    name: "Madagascar",
    emoji: "🇲🇬",
  },
  MH: {
    unicode: "U+1F1F2 U+1F1ED",
    name: "Marshall Islands",
    emoji: "🇲🇭",
  },
  MK: {
    unicode: "U+1F1F2 U+1F1F0",
    name: "Macedonia",
    emoji: "🇲🇰",
  },
  ML: {
    unicode: "U+1F1F2 U+1F1F1",
    name: "Mali",
    emoji: "🇲🇱",
  },
  MM: {
    unicode: "U+1F1F2 U+1F1F2",
    name: "Myanmar (Burma)",
    emoji: "🇲🇲",
  },
  MN: {
    unicode: "U+1F1F2 U+1F1F3",
    name: "Mongolia",
    emoji: "🇲🇳",
  },
  MO: {
    unicode: "U+1F1F2 U+1F1F4",
    name: "Macau SAR China",
    emoji: "🇲🇴",
  },
  MP: {
    unicode: "U+1F1F2 U+1F1F5",
    name: "Northern Mariana Islands",
    emoji: "🇲🇵",
  },
  MQ: {
    unicode: "U+1F1F2 U+1F1F6",
    name: "Martinique",
    emoji: "🇲🇶",
  },
  MR: {
    unicode: "U+1F1F2 U+1F1F7",
    name: "Mauritania",
    emoji: "🇲🇷",
  },
  MS: {
    unicode: "U+1F1F2 U+1F1F8",
    name: "Montserrat",
    emoji: "🇲🇸",
  },
  MT: {
    unicode: "U+1F1F2 U+1F1F9",
    name: "Malta",
    emoji: "🇲🇹",
  },
  MU: {
    unicode: "U+1F1F2 U+1F1FA",
    name: "Mauritius",
    emoji: "🇲🇺",
  },
  MV: {
    unicode: "U+1F1F2 U+1F1FB",
    name: "Maldives",
    emoji: "🇲🇻",
  },
  MW: {
    unicode: "U+1F1F2 U+1F1FC",
    name: "Malawi",
    emoji: "🇲🇼",
  },
  MX: {
    unicode: "U+1F1F2 U+1F1FD",
    name: "Mexico",
    emoji: "🇲🇽",
  },
  MY: {
    unicode: "U+1F1F2 U+1F1FE",
    name: "Malaysia",
    emoji: "🇲🇾",
  },
  MZ: {
    unicode: "U+1F1F2 U+1F1FF",
    name: "Mozambique",
    emoji: "🇲🇿",
  },
  NA: {
    unicode: "U+1F1F3 U+1F1E6",
    name: "Namibia",
    emoji: "🇳🇦",
  },
  NC: {
    unicode: "U+1F1F3 U+1F1E8",
    name: "New Caledonia",
    emoji: "🇳🇨",
  },
  NE: {
    unicode: "U+1F1F3 U+1F1EA",
    name: "Niger",
    emoji: "🇳🇪",
  },
  NF: {
    unicode: "U+1F1F3 U+1F1EB",
    name: "Norfolk Island",
    emoji: "🇳🇫",
  },
  NG: {
    unicode: "U+1F1F3 U+1F1EC",
    name: "Nigeria",
    emoji: "🇳🇬",
  },
  NI: {
    unicode: "U+1F1F3 U+1F1EE",
    name: "Nicaragua",
    emoji: "🇳🇮",
  },
  NL: {
    unicode: "U+1F1F3 U+1F1F1",
    name: "Netherlands",
    emoji: "🇳🇱",
  },
  NO: {
    unicode: "U+1F1F3 U+1F1F4",
    name: "Norway",
    emoji: "🇳🇴",
  },
  NP: {
    unicode: "U+1F1F3 U+1F1F5",
    name: "Nepal",
    emoji: "🇳🇵",
  },
  NR: {
    unicode: "U+1F1F3 U+1F1F7",
    name: "Nauru",
    emoji: "🇳🇷",
  },
  NU: {
    unicode: "U+1F1F3 U+1F1FA",
    name: "Niue",
    emoji: "🇳🇺",
  },
  NZ: {
    unicode: "U+1F1F3 U+1F1FF",
    name: "New Zealand",
    emoji: "🇳🇿",
  },
  OM: {
    unicode: "U+1F1F4 U+1F1F2",
    name: "Oman",
    emoji: "🇴🇲",
  },
  PA: {
    unicode: "U+1F1F5 U+1F1E6",
    name: "Panama",
    emoji: "🇵🇦",
  },
  PE: {
    unicode: "U+1F1F5 U+1F1EA",
    name: "Peru",
    emoji: "🇵🇪",
  },
  PF: {
    unicode: "U+1F1F5 U+1F1EB",
    name: "French Polynesia",
    emoji: "🇵🇫",
  },
  PG: {
    unicode: "U+1F1F5 U+1F1EC",
    name: "Papua New Guinea",
    emoji: "🇵🇬",
  },
  PH: {
    unicode: "U+1F1F5 U+1F1ED",
    name: "Philippines",
    emoji: "🇵🇭",
  },
  PK: {
    unicode: "U+1F1F5 U+1F1F0",
    name: "Pakistan",
    emoji: "🇵🇰",
  },
  PL: {
    unicode: "U+1F1F5 U+1F1F1",
    name: "Poland",
    emoji: "🇵🇱",
  },
  PM: {
    unicode: "U+1F1F5 U+1F1F2",
    name: "St. Pierre & Miquelon",
    emoji: "🇵🇲",
  },
  PN: {
    unicode: "U+1F1F5 U+1F1F3",
    name: "Pitcairn Islands",
    emoji: "🇵🇳",
  },
  PR: {
    unicode: "U+1F1F5 U+1F1F7",
    name: "Puerto Rico",
    emoji: "🇵🇷",
  },
  PS: {
    unicode: "U+1F1F5 U+1F1F8",
    name: "Palestinian Territories",
    emoji: "🇵🇸",
  },
  PT: {
    unicode: "U+1F1F5 U+1F1F9",
    name: "Portugal",
    emoji: "🇵🇹",
  },
  PW: {
    unicode: "U+1F1F5 U+1F1FC",
    name: "Palau",
    emoji: "🇵🇼",
  },
  PY: {
    unicode: "U+1F1F5 U+1F1FE",
    name: "Paraguay",
    emoji: "🇵🇾",
  },
  QA: {
    unicode: "U+1F1F6 U+1F1E6",
    name: "Qatar",
    emoji: "🇶🇦",
  },
  RE: {
    unicode: "U+1F1F7 U+1F1EA",
    name: "Réunion",
    emoji: "🇷🇪",
  },
  RO: {
    unicode: "U+1F1F7 U+1F1F4",
    name: "Romania",
    emoji: "🇷🇴",
  },
  RS: {
    unicode: "U+1F1F7 U+1F1F8",
    name: "Serbia",
    emoji: "🇷🇸",
  },
  RU: {
    unicode: "U+1F1F7 U+1F1FA",
    name: "Russia",
    emoji: "🇷🇺",
  },
  RW: {
    unicode: "U+1F1F7 U+1F1FC",
    name: "Rwanda",
    emoji: "🇷🇼",
  },
  SA: {
    unicode: "U+1F1F8 U+1F1E6",
    name: "Saudi Arabia",
    emoji: "🇸🇦",
  },
  SB: {
    unicode: "U+1F1F8 U+1F1E7",
    name: "Solomon Islands",
    emoji: "🇸🇧",
  },
  SC: {
    unicode: "U+1F1F8 U+1F1E8",
    name: "Seychelles",
    emoji: "🇸🇨",
  },
  SD: {
    unicode: "U+1F1F8 U+1F1E9",
    name: "Sudan",
    emoji: "🇸🇩",
  },
  SE: {
    unicode: "U+1F1F8 U+1F1EA",
    name: "Sweden",
    emoji: "🇸🇪",
  },
  SG: {
    unicode: "U+1F1F8 U+1F1EC",
    name: "Singapore",
    emoji: "🇸🇬",
  },
  SH: {
    unicode: "U+1F1F8 U+1F1ED",
    name: "St. Helena",
    emoji: "🇸🇭",
  },
  SI: {
    unicode: "U+1F1F8 U+1F1EE",
    name: "Slovenia",
    emoji: "🇸🇮",
  },
  SJ: {
    unicode: "U+1F1F8 U+1F1EF",
    name: "Svalbard & Jan Mayen",
    emoji: "🇸🇯",
  },
  SK: {
    unicode: "U+1F1F8 U+1F1F0",
    name: "Slovakia",
    emoji: "🇸🇰",
  },
  SL: {
    unicode: "U+1F1F8 U+1F1F1",
    name: "Sierra Leone",
    emoji: "🇸🇱",
  },
  SM: {
    unicode: "U+1F1F8 U+1F1F2",
    name: "San Marino",
    emoji: "🇸🇲",
  },
  SMA: {
    unicode: "U+1F1F8 U+1F1F2",
    name: "Cruise Ship",
    emoji: "⛴",
  },
  SN: {
    unicode: "U+1F1F8 U+1F1F3",
    name: "Senegal",
    emoji: "🇸🇳",
  },
  SO: {
    unicode: "U+1F1F8 U+1F1F4",
    name: "Somalia",
    emoji: "🇸🇴",
  },
  SR: {
    unicode: "U+1F1F8 U+1F1F7",
    name: "Suriname",
    emoji: "🇸🇷",
  },
  SS: {
    unicode: "U+1F1F8 U+1F1F8",
    name: "South Sudan",
    emoji: "🇸🇸",
  },
  ST: {
    unicode: "U+1F1F8 U+1F1F9",
    name: "São Tomé & Príncipe",
    emoji: "🇸🇹",
  },
  SV: {
    unicode: "U+1F1F8 U+1F1FB",
    name: "El Salvador",
    emoji: "🇸🇻",
  },
  SX: {
    unicode: "U+1F1F8 U+1F1FD",
    name: "Sint Maarten",
    emoji: "🇸🇽",
  },
  SY: {
    unicode: "U+1F1F8 U+1F1FE",
    name: "Syria",
    emoji: "🇸🇾",
  },
  SZ: {
    unicode: "U+1F1F8 U+1F1FF",
    name: "Swaziland",
    emoji: "🇸🇿",
  },
  TA: {
    unicode: "U+1F1F9 U+1F1E6",
    name: "Tristan da Cunha",
    emoji: "🇹🇦",
  },
  TC: {
    unicode: "U+1F1F9 U+1F1E8",
    name: "Turks & Caicos Islands",
    emoji: "🇹🇨",
  },
  TD: {
    unicode: "U+1F1F9 U+1F1E9",
    name: "Chad",
    emoji: "🇹🇩",
  },
  TF: {
    unicode: "U+1F1F9 U+1F1EB",
    name: "French Southern Territories",
    emoji: "🇹🇫",
  },
  TG: {
    unicode: "U+1F1F9 U+1F1EC",
    name: "Togo",
    emoji: "🇹🇬",
  },
  TH: {
    unicode: "U+1F1F9 U+1F1ED",
    name: "Thailand",
    emoji: "🇹🇭",
  },
  TJ: {
    unicode: "U+1F1F9 U+1F1EF",
    name: "Tajikistan",
    emoji: "🇹🇯",
  },
  TK: {
    unicode: "U+1F1F9 U+1F1F0",
    name: "Tokelau",
    emoji: "🇹🇰",
  },
  TL: {
    unicode: "U+1F1F9 U+1F1F1",
    name: "Timor-Leste",
    emoji: "🇹🇱",
  },
  TM: {
    unicode: "U+1F1F9 U+1F1F2",
    name: "Turkmenistan",
    emoji: "🇹🇲",
  },
  TN: {
    unicode: "U+1F1F9 U+1F1F3",
    name: "Tunisia",
    emoji: "🇹🇳",
  },
  TO: {
    unicode: "U+1F1F9 U+1F1F4",
    name: "Tonga",
    emoji: "🇹🇴",
  },
  TR: {
    unicode: "U+1F1F9 U+1F1F7",
    name: "Turkey",
    emoji: "🇹🇷",
  },
  TT: {
    unicode: "U+1F1F9 U+1F1F9",
    name: "Trinidad & Tobago",
    emoji: "🇹🇹",
  },
  TV: {
    unicode: "U+1F1F9 U+1F1FB",
    name: "Tuvalu",
    emoji: "🇹🇻",
  },
  TW: {
    unicode: "U+1F1F9 U+1F1FC",
    name: "Taiwan",
    emoji: "🇹🇼",
  },
  TZ: {
    unicode: "U+1F1F9 U+1F1FF",
    name: "Tanzania",
    emoji: "🇹🇿",
  },
  UA: {
    unicode: "U+1F1FA U+1F1E6",
    name: "Ukraine",
    emoji: "🇺🇦",
  },
  UG: {
    unicode: "U+1F1FA U+1F1EC",
    name: "Uganda",
    emoji: "🇺🇬",
  },
  UM: {
    unicode: "U+1F1FA U+1F1F2",
    name: "U.S. Outlying Islands",
    emoji: "🇺🇲",
  },
  UN: {
    unicode: "U+1F1FA U+1F1F3",
    name: "United Nations",
    emoji: "🇺🇳",
  },
  US: {
    unicode: "U+1F1FA U+1F1F8",
    name: "USA",
    emoji: "🇺🇸",
  },
  UY: {
    unicode: "U+1F1FA U+1F1FE",
    name: "Uruguay",
    emoji: "🇺🇾",
  },
  UZ: {
    unicode: "U+1F1FA U+1F1FF",
    name: "Uzbekistan",
    emoji: "🇺🇿",
  },
  VA: {
    unicode: "U+1F1FB U+1F1E6",
    name: "Vatican City",
    emoji: "🇻🇦",
  },
  VC: {
    unicode: "U+1F1FB U+1F1E8",
    name: "St. Vincent & Grenadines",
    emoji: "🇻🇨",
  },
  VE: {
    unicode: "U+1F1FB U+1F1EA",
    name: "Venezuela",
    emoji: "🇻🇪",
  },
  VG: {
    unicode: "U+1F1FB U+1F1EC",
    name: "British Virgin Islands",
    emoji: "🇻🇬",
  },
  VI: {
    unicode: "U+1F1FB U+1F1EE",
    name: "U.S. Virgin Islands",
    emoji: "🇻🇮",
  },
  VN: {
    unicode: "U+1F1FB U+1F1F3",
    name: "Vietnam",
    emoji: "🇻🇳",
  },
  VU: {
    unicode: "U+1F1FB U+1F1FA",
    name: "Vanuatu",
    emoji: "🇻🇺",
  },
  WF: {
    unicode: "U+1F1FC U+1F1EB",
    name: "Wallis & Futuna",
    emoji: "🇼🇫",
  },
  WS: {
    unicode: "U+1F1FC U+1F1F8",
    name: "Samoa",
    emoji: "🇼🇸",
  },
  XK: {
    unicode: "U+1F1FD U+1F1F0",
    name: "Kosovo",
    emoji: "🇽🇰",
  },
  YE: {
    unicode: "U+1F1FE U+1F1EA",
    name: "Yemen",
    emoji: "🇾🇪",
  },
  YT: {
    unicode: "U+1F1FE U+1F1F9",
    name: "Mayotte",
    emoji: "🇾🇹",
  },
  ZA: {
    unicode: "U+1F1FF U+1F1E6",
    name: "South Africa",
    emoji: "🇿🇦",
  },
  ZM: {
    unicode: "U+1F1FF U+1F1F2",
    name: "Zambia",
    emoji: "🇿🇲",
  },
  ZW: {
    unicode: "U+1F1FF U+1F1FC",
    name: "Zimbabwe",
    emoji: "🇿🇼",
  },
});
